language: php
php:
  - 7.2

services:
  - postgresql

addons:
  postgresql: "10"

cache:
  directories:
    - node_modules
    - vendor

before_script:
  # todo lint
  #- cp .env.travis .env
  - psql -c 'create database travis_ci_test;' -U postgres
  #- composer self-update
  #- composer install --no-interaction
  #- php artisan migrate --no-interaction -vvv

#script:
#  - vendor/bin/phpunit